# Generated by Django 5.1.1 on 2024-09-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_show_name_remove_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='show_name',
        ),
    ]
